### ISSUE TITLE
Time convert

### ISSUE THREAD

**Issue by rcbgr** [jc-cb/prime-workshop-scripts#2]
https://github.com/jc-cb/prime-workshop-scripts/blob/26056f6e18396ca284d4d2ed9c5a4e50a292a310/prime_create_order.py#L26

**Comment by nmorgan-cb** [comment]
One option to fix: https://www.tutorialspoint.com/python/time_strftime.htm#:~:text=Pythom%20time%20method%20strftime(),format%20must%20be%20a%20string.

**Comment by jc-cb** [comment]
time.time() is a float. I am converting to int and then string. 

alternative is 

s = time.gmtime(time.time())
TIMESTAMP = time.strftime('%Y-%m-%dT%H:%M:%SZ', s) 

which is in my opinion much less easy to interpret
